import os
import json

def generate_html_report(results: dict) -> str:
    """
    Generate a full HTML report from DANY pipeline results.

    Args:
        results (dict): Full results dictionary from run_dany_pipeline.

    Returns:
        str: Path to the generated HTML report.
    """

    # Ensure output directory exists
    os.makedirs("outputs", exist_ok=True)
    report_path = os.path.join("outputs", "dany_report.html")

    # Open file for writing
    with open(report_path, "w", encoding="utf-8") as f:
        # HTML header
        f.write("<html><head><title>DANY Report</title></head><body>\n")
        f.write("<h1>DANY Report</h1>\n")
        
        # ======================================================
        # Target Validation
        # ======================================================
        f.write("<h2>Target Validation</h2>\n")
        target_validation = results.get("target_validation", {})
        f.write("<pre>{}</pre>\n".format(json.dumps(target_validation, indent=2)))
        
        # ======================================================
        # Cleaning Report
        # ======================================================
        f.write("<h2>Cleaning Report</h2>\n")
        cleaning = results.get("cleaning", [])
        if cleaning:
            f.write("<pre>{}</pre>\n".format(json.dumps(cleaning, indent=2)))
        else:
            f.write("<p>No cleaning actions were performed.</p>\n")

        # ======================================================
        # EDA Profiles
        # ======================================================
        f.write("<h2>EDA Profiles</h2>\n")
        profiles = results.get("profiles", {})
        if profiles:
            f.write("<pre>{}</pre>\n".format(json.dumps(profiles, indent=2)))
        else:
            f.write("<p>No EDA profiles generated.</p>\n")

        # ======================================================
        # Modeling Results
        # ======================================================
        f.write("<h2>Modeling Results</h2>\n")
        modeling = results.get("modeling", {})
        if modeling:
            # For better readability, remove the actual pipeline object
            safe_modeling = modeling.copy()
            if "all_models_results" in safe_modeling:
                for model in safe_modeling["all_models_results"]:
                    if "pipeline" in model:
                        model["pipeline"] = str(model["pipeline"])
            if "best_pipeline" in safe_modeling:
                safe_modeling["best_pipeline"] = str(safe_modeling["best_pipeline"])
            f.write("<pre>{}</pre>\n".format(json.dumps(safe_modeling, indent=2)))
        else:
            f.write("<p>No modeling results generated.</p>\n")

        # ======================================================
        # Footer
        # ======================================================
        f.write("<hr><p>Report generated by DANY pipeline</p>\n")
        f.write("</body></html>\n")

    return report_path
